#!/usr/bin/env /usr/bin/python3
from factorize_all import factorize_all
from sys import argv
import time

if __name__ == "__main__":
    try:
        with open(argv[1]) as file:
            line = file.readline()

            while line != "":
                value = int(line.split('\n')[0])
                factorize_all(value)    
                line = file.readline()
    except:
        pass

    start_time = time.time()

    for ln in line:
        num = int(ln.strip())
        factors = factorize_all(num)
        if factors:
            print(f"{num}={factors[0]}*{factors[1]}")


        if time.time() - start_time > 5:
            print("Time limit exceeded")
            exit()
