#!/usr/bin/env /usr/bin/python3
from factorize_all import read_and_print_file


if __name__ == "__main__":
    file_path = "tests/test00"
    if len(file_path.split()) != 1:
        print("Usage: python script.py <file_path>")
        exit(1)
    read_and_print_file(file_path)
